"""esquema inicial

Revision ID: 0001_initial
Revises: 
Create Date: 2026-06-10 07:48:50.217599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de la revisión, usados por Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postulaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vacante_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('postulado', 'en_revision', 'entrevista', 'aceptado', 'rechazado', 'retirado', name='estado_postulacion_enum'), nullable=False),
    sa.Column('nota_estudiante', sa.Text(), nullable=True),
    sa.Column('nota_empresa', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacante_id', 'estudiante_id', name='uq_postulacion_vacante_estudiante')
    )
    op.create_index(op.f('ix_postulaciones_empresa_id'), 'postulaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_postulaciones_estado'), 'postulaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_postulaciones_estudiante_id'), 'postulaciones', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_postulaciones_vacante_id'), 'postulaciones', ['vacante_id'], unique=False)
    op.create_table('documentos_postulacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('postulacion_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('carta_presentacion', 'hoja_de_vida', 'portafolio', name='tipo_doc_postulacion_enum'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_estados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('postulacion_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('postulado', 'en_revision', 'entrevista', 'aceptado', 'rechazado', 'retirado', name='estado_post_anterior_enum'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('postulado', 'en_revision', 'entrevista', 'aceptado', 'rechazado', 'retirado', name='estado_post_nuevo_enum'), nullable=False),
    sa.Column('cambiado_por', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_estados')
    op.drop_table('documentos_postulacion')
    op.drop_index(op.f('ix_postulaciones_vacante_id'), table_name='postulaciones')
    op.drop_index(op.f('ix_postulaciones_estudiante_id'), table_name='postulaciones')
    op.drop_index(op.f('ix_postulaciones_estado'), table_name='postulaciones')
    op.drop_index(op.f('ix_postulaciones_empresa_id'), table_name='postulaciones')
    op.drop_table('postulaciones')
    # ### end Alembic commands ###
